version: "3"

services:
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    env_file:
      - ../../api/.env
    ports:
      - 3001:3001
  web:
    build:
      context: ../../web
      dockerfile: Dockerfile
    env_file:
      - ../../web/.env
    ports:
      - 3000:3000
